version: 2

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - copyloopvar
    - errname
    - gosec
    - noctx
    - dupl
    - whitespace

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    enable-all: true
  gosec:
    exclude: -G104

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
